version: '2'

services:

  nagios:
    container_name: nagios
    image: nagios
    build: .
    ports:
      - "8080:80"

    volumes:
      - "./nagios.cfg:/opt/nagios/etc/nagios.cfg"
#    environment:
##      - ACCEPT_EULA=Y
#      - SA_PASSWORD=Fatfrog99
#    network_mode: host

#networks:
#
#  capnet:
#    external:
#      name: capnet
